%% Lissajous curves by KalMa    #MatFunZone (2019)
%  contact: maciej.kalarus@gmail.com
%  ------------------------------------------------------------------------

function Lissajous
    global Lissajous
    
    Lissajous.Name          = 'MatLissajous';
    Lissajous.Version       = 1;
    Lissajous.FPS           = 20;               % [frames per second]

    %% Board
    Board.Size    = [500 500];        % [X Y] [pixels]
    Board.Color   = [0.9 0.9 0.9];

    Lissajous.Panel.Width   = 220;
    Lissajous.Panel.Color   = [0.7 0.7 0.7];
    Lissajous.Control.Left  = Board.Size(1) + 6;
    Lissajous.Control.Top   = Board.Size(1) - 20;

    Lissajous.CurveStyle    = struct('Color',[0 0.5 0], 'LineStyle','-');
    Lissajous.CommonStyle   = struct('Units','pixels','BackgroundColor', Lissajous.Panel.Color);
    
    %% application window
    ScreenSize = get(0,'ScreenSize');
    S = Board.Size;
    figure( 'Units','pixels',...
            'Position',[(ScreenSize(3:4) - S - [Lissajous.Panel.Width, 0])*0.5, S] + [0 0 Lissajous.Panel.Width 35],...
            'MenuBar','none',...
            'NumberTitle','off',...
            'Resize','off',...
            'Color',Lissajous.Panel.Color,...
            'Name',sprintf('%s by KalMa (v%0.1f)', Lissajous.Name, Lissajous.Version),...
            'CloseRequestFcn',@(~,~)CloseApp());
    
    axes( 'Units','pixels',...
          'Position',[5 5 S-1],...
          'NextPlot','add',...
          'box','on',...
          'Color',Board.Color,...
          'xlim',[-11 11],...
          'ylim',[-11 11],...
          'XTick',[],...
          'YTick',[]);
       
    title('x(t) = A_xsin(n_xt + \phi),  y(t) = A_ysin(n_yt)');
    ln = linspace(-1,1,361);
    Lissajous.hCurve = line(ln,ln,Lissajous.CurveStyle);

    %% controls
    Left = Lissajous.Control.Left+5;
    Top  = Lissajous.Control.Top;
    Lissajous.dPhase = CuiControl('phi [deg]', [Left, Top], -180, 180, 90);
    Lissajous.Ax   = CuiControl('Ax', [Left, Top - 70], 1, 10, 10);
    Lissajous.Ay   = CuiControl('Ay', [Left, Top - 100], 1, 10, 10);
    Lissajous.nx   = CuiControl('nx', [Left, Top - 140], 1, 10, 1);
    Lissajous.ny   = CuiControl('ny', [Left, Top - 170], 1, 10, 1);

    Lissajous.Auto   = uicontrol(...
        'Units','pixels',...
        'Style','checkbox',...
        'Position',[Left+50, Top - 30, 60, 20],...
        'String','auto',...
        'BackgroundColor', Lissajous.Panel.Color);
        
    %% Timer
    Lissajous.hTimer = timer(...
        'Period',1/Lissajous.FPS,...
        'ExecutionMode','fixedRate',...
        'TimerFcn',@(~,~)Show());
    
    start(Lissajous.hTimer);
end

function Show()
    global Lissajous
    if (Lissajous.Auto.Value)
        v = Lissajous.dPhase.Value+1;
        if (v > Lissajous.dPhase.Max)
            v = Lissajous.dPhase.Min;
        end
        Lissajous.dPhase.Value = v;
        change(Lissajous.dPhase);
    end
    
    S = 0:1:360;
    x = Lissajous.Ax.Value * sind(Lissajous.dPhase.Value + S*round(Lissajous.nx.Value));
    y = Lissajous.Ay.Value * sind(S*round(Lissajous.ny.Value));
    
    set(Lissajous.hCurve,'XData',x,'YData',y');
end

function CloseApp()
    global Lissajous
    stop(Lissajous.hTimer);
    delete(gcf);
end

function h = CuiControl(name, position, min, max, value)
    global Lissajous
    Control.Width = Lissajous.Panel.Width - 100;
    uicontrol(Lissajous.CommonStyle,...
        'Style','text',...
        'Position',[position,45,20],...
        'HorizontalAlignment','right',...
        'String',name);

    hv = uicontrol(Lissajous.CommonStyle,...
        'Style','text',...
        'Position',[position + [Control.Width+55,0],60,20],...
        'HorizontalAlignment','left',...
        'String',sprintf("%d",round(value)));

    h = uicontrol(Lissajous.CommonStyle,...
        'Style','slider',...
        'Min',min,...
        'Max',max,...
        'SliderStep',[1/(max-min),1/(max-min)*5],...
        'Position',[position + [50 4], Control.Width,20],...
        'Value',value,...
        'UserData',hv,...
        'Callback',@(src,~)change(src));
end

function change(src)
    src.UserData.String = sprintf("%d",round(src.Value));
end
